database:
  host: "45.136.205.42"
  port: 3306
  user: "ngaek"
  password: "ngaek"
  name: "ngaek"
server:
  port: ":8080"

admin_api:
  key: "JDFKEinDIE@DWNSbhdcUY2982e"

site:
  gris:
    number: "6141303612"
    registration_date: "19.09.2013"
    show_placeholder_if_empty: true
  admin_email: "info@ngaek.by"
  phone: "+375 (17) 123-45-67"
  phone_tel: "+375171234567"
  one_window_external_url: "https://minsk.gov.by/ru/services/okno/"